package com.scyb.aisweather.webservice.client.ShiftAidsMarkedDynamic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T11:31:00.124+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IShiftAidsMarkedDynamic")
@XmlSeeAlso({ObjectFactory.class})
public interface IShiftAidsMarkedDynamic {

    @WebMethod
    @RequestWrapper(localName = "shiftAmdBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.ShiftAidsMarkedDynamic.ShiftAmdBroadcastService")
    @ResponseWrapper(localName = "shiftAmdBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.ShiftAidsMarkedDynamic.ShiftAmdBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String shiftAmdBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            ShiftDynamicBo arg0
    );
}
