package com.scyb.aisweather.webservice.client.ConstructionWork;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T14:01:29.112+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IConstructionWork")
@XmlSeeAlso({ObjectFactory.class})
public interface IConstructionWork {

    @WebMethod
    @RequestWrapper(localName = "workBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.ConstructionWork.WorkBroadcastService")
    @ResponseWrapper(localName = "workBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.ConstructionWork.WorkBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String workBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            ConstructionWorkBo arg0
    );
}
