
package com.scyb.aisweather.webservice.client.MarineWeatherForecast;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-06-17T16:55:16.258+08:00
 * Generated source version: 2.5.1
 * 
 */
public final class IMarineWeatherForecast_MarineWeatherForecastImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.aisweather.scyb.com/", "MarineWeatherForecastImplService");

    private IMarineWeatherForecast_MarineWeatherForecastImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MarineWeatherForecastImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MarineWeatherForecastImplService ss = new MarineWeatherForecastImplService(wsdlURL, SERVICE_NAME);
        IMarineWeatherForecast port = ss.getMarineWeatherForecastImplPort();  
        
        {
        System.out.println("Invoking mwfBroadcastService...");
        MarineWeatherForecastBo _mwfBroadcastService_arg0 = null;
        int _mwfBroadcastService__return = port.mwfBroadcastService(_mwfBroadcastService_arg0);
        System.out.println("mwfBroadcastService.result=" + _mwfBroadcastService__return);


        }

        System.exit(0);
    }

}
