package com.scyb.aisweather.webservice.client.MarineWeatherForecast;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-06-17T16:55:16.328+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IMarineWeatherForecast")
@XmlSeeAlso({ObjectFactory.class})
public interface IMarineWeatherForecast {

    @WebMethod
    @RequestWrapper(localName = "mwfBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.MarineWeatherForecast.MwfBroadcastService")
    @ResponseWrapper(localName = "mwfBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.MarineWeatherForecast.MwfBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int mwfBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            MarineWeatherForecastBo arg0
    );
}
