package com.scyb.aisweather.webservice.client.AreaRound;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T14:57:20.486+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "DemarcatedRoundImplService", 
                  wsdlLocation = "http://localhost:8080/services/dr?wsdl",
                  targetNamespace = "http://impl.webservice.aisweather.scyb.com/") 
public class DemarcatedRoundImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.aisweather.scyb.com/", "DemarcatedRoundImplService");
    public final static QName DemarcatedRoundImplPort = new QName("http://impl.webservice.aisweather.scyb.com/", "DemarcatedRoundImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/dr?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemarcatedRoundImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/dr?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemarcatedRoundImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemarcatedRoundImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemarcatedRoundImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DemarcatedRoundImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DemarcatedRoundImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DemarcatedRoundImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IDemarcatedRound
     */
    @WebEndpoint(name = "DemarcatedRoundImplPort")
    public IDemarcatedRound getDemarcatedRoundImplPort() {
        return super.getPort(DemarcatedRoundImplPort, IDemarcatedRound.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDemarcatedRound
     */
    @WebEndpoint(name = "DemarcatedRoundImplPort")
    public IDemarcatedRound getDemarcatedRoundImplPort(WebServiceFeature... features) {
        return super.getPort(DemarcatedRoundImplPort, IDemarcatedRound.class, features);
    }

}
