package com.scyb.aisweather.webservice.client.AreaRound;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T14:57:20.459+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IDemarcatedRound")
@XmlSeeAlso({ObjectFactory.class})
public interface IDemarcatedRound {

    @WebMethod
    @RequestWrapper(localName = "roundAreaBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.AreaRound.RoundAreaBroadcastService")
    @ResponseWrapper(localName = "roundAreaBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.AreaRound.RoundAreaBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String roundAreaBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            DemarcatedRoundBo arg0
    );
}
