package com.scyb.aisweather.webservice.client.InternationalText;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-04-13T12:35:39.025+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IInternationalText")
@XmlSeeAlso({ObjectFactory.class})
public interface IInternationalText {

    @WebMethod
    @RequestWrapper(localName = "iTextBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.InternationalText.ITextBroadcastService")
    @ResponseWrapper(localName = "iTextBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.InternationalText.ITextBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int iTextBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            com.scyb.aisweather.webservice.client.InternationalText.InternationalTextBo arg0
    );
}
