package com.scyb.aisweather.webservice.client.MilitaryActivitiy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T14:30:47.762+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IMilitaryActivitiy")
@XmlSeeAlso({ObjectFactory.class})
public interface IMilitaryActivitiy {

    @WebMethod
    @RequestWrapper(localName = "maBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.MilitaryActivitiy.MaBroadcastService")
    @ResponseWrapper(localName = "maBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.MilitaryActivitiy.MaBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String maBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            MilitaryActivitiyBo arg0
    );
}
