package com.scyb.aisweather.webservice.client.WarnWave;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-04-13T09:23:24.772+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IWaveWarn")
@XmlSeeAlso({ObjectFactory.class})
public interface IWaveWarn {

    @WebMethod
    @RequestWrapper(localName = "waveWarnBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.WarnWave.WaveWarnBroadcastService")
    @ResponseWrapper(localName = "waveWarnBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.WarnWave.WaveWarnBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String waveWarnBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            com.scyb.aisweather.webservice.client.WarnWave.WaveWarnBo arg0
    );
}
