package com.scyb.aisweather.webservice.client.WarnWave;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-04-13T09:23:24.820+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "WaveWarnImplService", 
                  wsdlLocation = "http://localhost:8080/services/waveWarn?wsdl",
                  targetNamespace = "http://impl.webservice.aisweather.scyb.com/") 
public class WaveWarnImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.aisweather.scyb.com/", "WaveWarnImplService");
    public final static QName WaveWarnImplPort = new QName("http://impl.webservice.aisweather.scyb.com/", "WaveWarnImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/waveWarn?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WaveWarnImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/waveWarn?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WaveWarnImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WaveWarnImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WaveWarnImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WaveWarnImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WaveWarnImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WaveWarnImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IWaveWarn
     */
    @WebEndpoint(name = "WaveWarnImplPort")
    public IWaveWarn getWaveWarnImplPort() {
        return super.getPort(WaveWarnImplPort, IWaveWarn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWaveWarn
     */
    @WebEndpoint(name = "WaveWarnImplPort")
    public IWaveWarn getWaveWarnImplPort(WebServiceFeature... features) {
        return super.getPort(WaveWarnImplPort, IWaveWarn.class, features);
    }

}
