package com.scyb.aisweather.webservice.client.WarnWind;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-04-13T09:12:57.642+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IWindWarn")
@XmlSeeAlso({ObjectFactory.class})
public interface IWindWarn {

    @WebMethod
    @RequestWrapper(localName = "windWarnBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.WarnWind.WindWarnBroadcastService")
    @ResponseWrapper(localName = "windWarnBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.WarnWind.WindWarnBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String windWarnBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            com.scyb.aisweather.webservice.client.WarnWind.WindWarnBo arg0
    );
}
