package com.scyb.aisweather.webservice.client.WarnStormSurge;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-04-13T09:42:09.751+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IStormSurgeWarn")
@XmlSeeAlso({ObjectFactory.class})
public interface IStormSurgeWarn {

    @WebMethod
    @RequestWrapper(localName = "ssWarnBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.WarnStormSurge.SsWarnBroadcastService")
    @ResponseWrapper(localName = "ssWarnBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.WarnStormSurge.SsWarnBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String ssWarnBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            StormSurgeWarnBo arg0
    );
}
