package com.scyb.aisweather.webservice.client.WarnStormSurge;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-04-13T09:42:09.790+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "StormSurgeWarnImplService", 
                  wsdlLocation = "http://localhost:8080/services/stormSurgeWarn?wsdl",
                  targetNamespace = "http://impl.webservice.aisweather.scyb.com/") 
public class StormSurgeWarnImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.aisweather.scyb.com/", "StormSurgeWarnImplService");
    public final static QName StormSurgeWarnImplPort = new QName("http://impl.webservice.aisweather.scyb.com/", "StormSurgeWarnImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/stormSurgeWarn?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StormSurgeWarnImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/stormSurgeWarn?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StormSurgeWarnImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StormSurgeWarnImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StormSurgeWarnImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StormSurgeWarnImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StormSurgeWarnImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StormSurgeWarnImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IStormSurgeWarn
     */
    @WebEndpoint(name = "StormSurgeWarnImplPort")
    public IStormSurgeWarn getStormSurgeWarnImplPort() {
        return super.getPort(StormSurgeWarnImplPort, IStormSurgeWarn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStormSurgeWarn
     */
    @WebEndpoint(name = "StormSurgeWarnImplPort")
    public IStormSurgeWarn getStormSurgeWarnImplPort(WebServiceFeature... features) {
        return super.getPort(StormSurgeWarnImplPort, IStormSurgeWarn.class, features);
    }

}
