
package com.scyb.aisweather.webservice.client.Ocean;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-06-15T12:44:26.821+08:00
 * Generated source version: 2.5.1
 * 
 */
public final class IOceanService_OceanServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.aisweather.scyb.com/", "OceanServiceImplService");

    private IOceanService_OceanServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = OceanServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OceanServiceImplService ss = new OceanServiceImplService(wsdlURL, SERVICE_NAME);
        IOceanService port = ss.getOceanServiceImplPort();  
        
        {
        System.out.println("Invoking oceanService...");
        javax.xml.datatype.XMLGregorianCalendar _oceanService_arg0 = null;
        java.util.List<com.scyb.aisweather.webservice.client.Ocean.Ocean> _oceanService__return = port.oceanService(_oceanService_arg0);
        System.out.println("oceanService.result=" + _oceanService__return);


        }

        System.exit(0);
    }

}
