package com.scyb.aisweather.webservice.client.Ocean;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-06-15T12:44:26.876+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IOceanService")
@XmlSeeAlso({ObjectFactory.class})
public interface IOceanService {

    @WebMethod
    @RequestWrapper(localName = "oceanService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.Ocean.OceanService")
    @ResponseWrapper(localName = "oceanServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.Ocean.OceanServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.scyb.aisweather.webservice.client.Ocean.Ocean> oceanService(
            @WebParam(name = "arg0", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg0
    );
}
