package com.scyb.aisweather.webservice.client.DgpsAidsMarkedDynamic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T11:42:06.228+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "DgpsAidsMarkedDynamicImplService", 
                  wsdlLocation = "http://localhost:8080/services/dgpsAmd?wsdl",
                  targetNamespace = "http://impl.webservice.aisweather.scyb.com/") 
public class DgpsAidsMarkedDynamicImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.aisweather.scyb.com/", "DgpsAidsMarkedDynamicImplService");
    public final static QName DgpsAidsMarkedDynamicImplPort = new QName("http://impl.webservice.aisweather.scyb.com/", "DgpsAidsMarkedDynamicImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/dgpsAmd?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DgpsAidsMarkedDynamicImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/dgpsAmd?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DgpsAidsMarkedDynamicImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DgpsAidsMarkedDynamicImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DgpsAidsMarkedDynamicImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DgpsAidsMarkedDynamicImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DgpsAidsMarkedDynamicImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DgpsAidsMarkedDynamicImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IDgpsAidsMarkedDynamic
     */
    @WebEndpoint(name = "DgpsAidsMarkedDynamicImplPort")
    public IDgpsAidsMarkedDynamic getDgpsAidsMarkedDynamicImplPort() {
        return super.getPort(DgpsAidsMarkedDynamicImplPort, IDgpsAidsMarkedDynamic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDgpsAidsMarkedDynamic
     */
    @WebEndpoint(name = "DgpsAidsMarkedDynamicImplPort")
    public IDgpsAidsMarkedDynamic getDgpsAidsMarkedDynamicImplPort(WebServiceFeature... features) {
        return super.getPort(DgpsAidsMarkedDynamicImplPort, IDgpsAidsMarkedDynamic.class, features);
    }

}
