package com.scyb.aisweather.webservice.client.DgpsAidsMarkedDynamic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T11:42:06.201+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IDgpsAidsMarkedDynamic")
@XmlSeeAlso({ObjectFactory.class})
public interface IDgpsAidsMarkedDynamic {

    @WebMethod
    @RequestWrapper(localName = "dgpsAmdBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.DgpsAidsMarkedDynamic.DgpsAmdBroadcastService")
    @ResponseWrapper(localName = "dgpsAmdBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.DgpsAidsMarkedDynamic.DgpsAmdBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String dgpsAmdBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            DgpsDynamicBo arg0
    );
}
