package com.scyb.aisweather.webservice.client.LightAidsMarkedDynamic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T11:53:57.962+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "LightAidsMarkedDynamicImplService", 
                  wsdlLocation = "http://localhost:8080/services/lightAmd?wsdl",
                  targetNamespace = "http://impl.webservice.aisweather.scyb.com/") 
public class LightAidsMarkedDynamicImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.aisweather.scyb.com/", "LightAidsMarkedDynamicImplService");
    public final static QName LightAidsMarkedDynamicImplPort = new QName("http://impl.webservice.aisweather.scyb.com/", "LightAidsMarkedDynamicImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/lightAmd?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LightAidsMarkedDynamicImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/lightAmd?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LightAidsMarkedDynamicImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LightAidsMarkedDynamicImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LightAidsMarkedDynamicImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LightAidsMarkedDynamicImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LightAidsMarkedDynamicImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LightAidsMarkedDynamicImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ILightAidsMarkedDynamic
     */
    @WebEndpoint(name = "LightAidsMarkedDynamicImplPort")
    public ILightAidsMarkedDynamic getLightAidsMarkedDynamicImplPort() {
        return super.getPort(LightAidsMarkedDynamicImplPort, ILightAidsMarkedDynamic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILightAidsMarkedDynamic
     */
    @WebEndpoint(name = "LightAidsMarkedDynamicImplPort")
    public ILightAidsMarkedDynamic getLightAidsMarkedDynamicImplPort(WebServiceFeature... features) {
        return super.getPort(LightAidsMarkedDynamicImplPort, ILightAidsMarkedDynamic.class, features);
    }

}
