
package com.scyb.aisweather.webservice.client.Coastal;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-06-16T09:30:16.330+08:00
 * Generated source version: 2.5.1
 * 
 */
public final class ICoastalService_CoastalServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.aisweather.scyb.com/", "CoastalServiceImplService");

    private ICoastalService_CoastalServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CoastalServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CoastalServiceImplService ss = new CoastalServiceImplService(wsdlURL, SERVICE_NAME);
        ICoastalService port = ss.getCoastalServiceImplPort();  
        
        {
        System.out.println("Invoking coastalService...");
        javax.xml.datatype.XMLGregorianCalendar _coastalService_arg0 = null;
        java.util.List<com.scyb.aisweather.webservice.client.Coastal.Coastal> _coastalService__return = port.coastalService(_coastalService_arg0);
        System.out.println("coastalService.result=" + _coastalService__return);


        }

        System.exit(0);
    }

}
