package com.scyb.aisweather.webservice.client.BaseAidsMarkedDynamic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T11:22:38.813+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IBaseAidsMarkedDynamic")
@XmlSeeAlso({ObjectFactory.class})
public interface IBaseAidsMarkedDynamic {

    @WebMethod
    @RequestWrapper(localName = "amdBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.BaseAidsMarkedDynamic.AmdBroadcastService")
    @ResponseWrapper(localName = "amdBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.BaseAidsMarkedDynamic.AmdBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String amdBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            BaseDynamicBo arg0
    );
}
