package com.scyb.aisweather.webservice.client.HydrologyWeatherForecast;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T11:15:58.229+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IHydrologyWeatherForecast")
@XmlSeeAlso({ObjectFactory.class})
public interface IHydrologyWeatherForecast {

    @WebMethod
    @RequestWrapper(localName = "hwfBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.HydrologyWeatherForecast.HwfBroadcastService")
    @ResponseWrapper(localName = "hwfBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.HydrologyWeatherForecast.HwfBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String hwfBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            HydrologyWeatherForecastBo arg0
    );
}
