
package com.scyb.aisweather.webservice.client.WarnSeaIce;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-05-28T13:55:25.397+08:00
 * Generated source version: 2.5.1
 * 
 */
public final class ISeaIceWarn_SeaIceWarnImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.aisweather.scyb.com/", "SeaIceWarnImplService");

    private ISeaIceWarn_SeaIceWarnImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SeaIceWarnImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SeaIceWarnImplService ss = new SeaIceWarnImplService(wsdlURL, SERVICE_NAME);
        ISeaIceWarn port = ss.getSeaIceWarnImplPort();  
        
        {
        System.out.println("Invoking seaIceWarnBroadcastService...");
        SeaIceWarnBo _seaIceWarnBroadcastService_arg0 = null;
        int _seaIceWarnBroadcastService__return = port.seaIceWarnBroadcastService(_seaIceWarnBroadcastService_arg0);
        System.out.println("seaIceWarnBroadcastService.result=" + _seaIceWarnBroadcastService__return);


        }

        System.exit(0);
    }

}
