package com.scyb.aisweather.webservice.client.WarnSeaIce;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-05-28T13:55:25.451+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "SeaIceWarnImplService", 
                  wsdlLocation = "http://localhost:8080/ais/services/seaIceWarn?wsdl",
                  targetNamespace = "http://impl.webservice.aisweather.scyb.com/") 
public class SeaIceWarnImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.aisweather.scyb.com/", "SeaIceWarnImplService");
    public final static QName SeaIceWarnImplPort = new QName("http://impl.webservice.aisweather.scyb.com/", "SeaIceWarnImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ais/services/seaIceWarn?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SeaIceWarnImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ais/services/seaIceWarn?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SeaIceWarnImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SeaIceWarnImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeaIceWarnImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SeaIceWarnImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SeaIceWarnImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SeaIceWarnImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ISeaIceWarn
     */
    @WebEndpoint(name = "SeaIceWarnImplPort")
    public ISeaIceWarn getSeaIceWarnImplPort() {
        return super.getPort(SeaIceWarnImplPort, ISeaIceWarn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISeaIceWarn
     */
    @WebEndpoint(name = "SeaIceWarnImplPort")
    public ISeaIceWarn getSeaIceWarnImplPort(WebServiceFeature... features) {
        return super.getPort(SeaIceWarnImplPort, ISeaIceWarn.class, features);
    }

}
