package com.scyb.aisweather.webservice.client.MarineEnvironmentForecast;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-06-18T14:45:25.130+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IMarineEnvironmentForecast")
@XmlSeeAlso({ObjectFactory.class})
public interface IMarineEnvironmentForecast {

    @WebMethod
    @RequestWrapper(localName = "mefBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.MarineEnvironmentForecast.MefBroadcastService")
    @ResponseWrapper(localName = "mefBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.MarineEnvironmentForecast.MefBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int mefBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            MarineEnvironmentForecastBo arg0
    );
}
