package com.scyb.aisweather.webservice.client.WarnFog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-04-13T09:33:46.393+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IFogWarn")
@XmlSeeAlso({ObjectFactory.class})
public interface IFogWarn {

    @WebMethod
    @RequestWrapper(localName = "fogWarnBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.WarnFog.FogWarnBroadcastService")
    @ResponseWrapper(localName = "fogWarnBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.WarnFog.FogWarnBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String fogWarnBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            com.scyb.aisweather.webservice.client.WarnFog.FogWarnBo arg0
    );
}
