package com.scyb.aisweather.webservice.client.WarnCold;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-04-13T09:55:31.220+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IColdWarn")
@XmlSeeAlso({ObjectFactory.class})
public interface IColdWarn {

    @WebMethod
    @RequestWrapper(localName = "coldWarnBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.WarnCold.ColdWarnBroadcastService")
    @ResponseWrapper(localName = "coldWarnBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.WarnCold.ColdWarnBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String coldWarnBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            ColdWarnBo arg0
    );
}
