package com.scyb.aisweather.webservice.client.AreaRectangle;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-12T15:21:16.244+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://webservice.aisweather.scyb.com/", name = "IDemarcatedRectangle")
@XmlSeeAlso({ObjectFactory.class})
public interface IDemarcatedRectangle {

    @WebMethod
    @RequestWrapper(localName = "rectangleAreaBroadcastService", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.AreaRectangle.RectangleAreaBroadcastService")
    @ResponseWrapper(localName = "rectangleAreaBroadcastServiceResponse", targetNamespace = "http://webservice.aisweather.scyb.com/", className = "com.scyb.aisweather.webservice.client.AreaRectangle.RectangleAreaBroadcastServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String rectangleAreaBroadcastService(
            @WebParam(name = "arg0", targetNamespace = "")
            com.scyb.aisweather.webservice.client.AreaRectangle.DemarcatedRectangleBo arg0
    );
}
